### ISSUE TITLE
Strange compilation error

### ISSUE THREAD

**Issue by kurtulmehtap** [xtrx-sdr/images#13]
I tried the necessary steps for compilation and  got a compilation error:
**fatal error: xtrx_api.h: No such file or directory**

Here are the details:
hp@hp:~$ git clone https://github.com/xtrx-sdr/images.git
Cloning into 'images'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 138 (delta 14), reused 31 (delta 7), pack-reused 94
Receiving objects: 100% (138/138), 4.51 MiB | 441.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
hp@hp:~$ git submodule init
fatal: Not a git repository (or any of the parent directories): .git
hp@hp:~$ cd images/
hp@hp:~/images$ git submodule init
Submodule 'sources/LMS7002M-driver' (https://github.com/xtrx-sdr/LMS7002M-driver) registered for path 'sources/LMS7002M-driver'
Submodule 'sources/liblms7002m' (https://github.com/xtrx-sdr/liblms7002m.git) registered for path 'sources/liblms7002m'
Submodule 'sources/libusb3380' (https://github.com/xtrx-sdr/libusb3380) registered for path 'sources/libusb3380'
Submodule 'sources/libxtrx' (https://github.com/xtrx-sdr/libxtrx) registered for path 'sources/libxtrx'
Submodule 'sources/libxtrxdsp' (https://github.com/xtrx-sdr/libxtrxdsp) registered for path 'sources/libxtrxdsp'
Submodule 'sources/libxtrxll' (https://github.com/xtrx-sdr/libxtrxll) registered for path 'sources/libxtrxll'
Submodule 'sources/xtrx_linux_pcie_drv' (https://github.com/xtrx-sdr/xtrx_linux_pcie_drv) registered for path 'sources/xtrx_linux_pcie_drv'
hp@hp:~/images$
hp@hp:~/images$ git submodule update
Cloning into 'sources/LMS7002M-driver'...
remote: Enumerating objects: 2412, done.
remote: Total 2412 (delta 0), reused 0 (delta 0), pack-reused 2412
Receiving objects: 100% (2412/2412), 18.15 MiB | 4.66 MiB/s, done.
Resolving deltas: 100% (1403/1403), done.
Checking connectivity... done.
Submodule path 'sources/LMS7002M-driver': checked out 'c244dfb92f84c027ede5faee7527a5947fc48480'
Cloning into 'sources/liblms7002m'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 38 (delta 14), reused 31 (delta 11), pack-reused 0
Unpacking objects: 100% (38/38), done.
Checking connectivity... done.
Submodule path 'sources/liblms7002m': checked out '07baade5df34946cbdd0c26753844a4de9e82ac0'
Cloning into 'sources/libusb3380'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 42 (delta 2), reused 4 (delta 2), pack-reused 33
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Submodule path 'sources/libusb3380': checked out '9e555415e438d88a9c98087b946642b00b5f9edf'
Cloning into 'sources/libxtrx'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 198 (delta 19), reused 29 (delta 12), pack-reused 154
Receiving objects: 100% (198/198), 171.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (109/109), done.
Checking connectivity... done.
Submodule path 'sources/libxtrx': checked out '54284cd3780d0ee3cbd5e5a2e103b2b08f032910'
Cloning into 'sources/libxtrxdsp'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 50 (delta 0), reused 1 (delta 0), pack-reused 47
Unpacking objects: 100% (50/50), done.
Checking connectivity... done.
Submodule path 'sources/libxtrxdsp': checked out '84c6f4c8bdb9e26e7c9a62bd96f02e35d61aaf45'
Cloning into 'sources/libxtrxll'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 222 (delta 13), reused 22 (delta 10), pack-reused 191
Receiving objects: 100% (222/222), 149.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (136/136), done.
Checking connectivity... done.
Submodule path 'sources/libxtrxll': checked out '5ba7b6f4bd5779b071871e7195bae4c19ffa153c'
Cloning into 'sources/xtrx_linux_pcie_drv'...
remote: Enumerating objects: 35, done.
remote: Total 35 (delta 0), reused 0 (delta 0), pack-reused 35
Unpacking objects: 100% (35/35), done.
Checking connectivity... done.
Submodule path 'sources/xtrx_linux_pcie_drv': checked out '815d8904c73f5749818e3cd8df1dfe83c14b19e4'
hp@hp:~/images$
hp@hp:~/images$ cd sources/
hp@hp:~/images/sources$ mkdir -p build
hp@hp:~/images/sources$ cd build
hp@hp:~/images/sources/build$
hp@hp:~/images/sources/build$ cmake -DINSTALL_UDEV_RULES=ON -DENABLE_SOAPY=NO ..-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building for x86_64
-- Building for x86_64
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/x86_64-linux-gnu/libusb-1.0.so
-- Building for x86_64
-- xtrxll: PCIe support enabled
-- xtrxll: USB3380 support enabled
-- Building for x86_64
-- Building for x86_64
-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
-- Building for x86_64
-- Found QCustomPlot: /usr/include
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/home/hp/images/sources/libxtrx/cmake/home/hp/images/sources/libxtrx/examples/xtrx_fft
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hp/images/sources/build
hp@hp:~/images/sources/build$
hp@hp:~/images/sources/build$ make
Scanning dependencies of target xtrxdsp
[  1%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp.c.o
[  2%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_filters.c.o
[  4%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_filters_data.c.o
[  5%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_no.c.o
[  7%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_x86_sse2.c.o
[  8%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_x86_avx.c.o
[  9%] Building C object libxtrxdsp/CMakeFiles/xtrxdsp.dir/xtrxdsp_x86_avx_fma.c.o
[ 11%] Linking C shared library libxtrxdsp.so
[ 11%] Built target xtrxdsp
Scanning dependencies of target test_filter
[ 12%] Building C object libxtrxdsp/tests/CMakeFiles/test_filter.dir/test_filter.c.o
[ 14%] Linking C executable test_filter
[ 14%] Built target test_filter
Scanning dependencies of target test_xtrxdsp_sc32i_iq16
[ 15%] Building C object libxtrxdsp/tests/CMakeFiles/test_xtrxdsp_sc32i_iq16.dir/test_xtrxdsp_sc32i_iq16.c.o
[ 16%] Linking C executable test_xtrxdsp_sc32i_iq16
[ 16%] Built target test_xtrxdsp_sc32i_iq16
Scanning dependencies of target usb3380
[ 18%] Building C object libusb3380/CMakeFiles/usb3380.dir/libusb3380.c.o
[ 19%] Linking C shared library libusb3380.so
[ 19%] Built target usb3380
Scanning dependencies of target test_libusb3380
[ 21%] Building C object libusb3380/CMakeFiles/test_libusb3380.dir/test_libusb3380.c.o
[ 22%] Linking C executable test_libusb3380
[ 22%] Built target test_libusb3380
Scanning dependencies of target xtrxll_libusb3380
[ 23%] Building C object libxtrxll/mod_usb3380/CMakeFiles/xtrxll_libusb3380.dir/xtrxll_libusb3380.c.o
[ 25%] Linking C static library libxtrxll_libusb3380.a
[ 25%] Built target xtrxll_libusb3380
Scanning dependencies of target xtrxll_pcie
[ 26%] Building C object libxtrxll/mod_pcie/CMakeFiles/xtrxll_pcie.dir/xtrxll_pcie_linux.c.o
[ 28%] Linking C static library libxtrxll_pcie.a
[ 28%] Built target xtrxll_pcie
Scanning dependencies of target xtrxll
[ 29%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_log.c.o
[ 30%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_port.c.o
[ 32%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_base.c.o
[ 33%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_base_pcie.c.o
[ 35%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_mmcm.c.o
[ 36%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_flash.c.o
[ 38%] Building C object libxtrxll/CMakeFiles/xtrxll.dir/xtrxll_api.c.o
[ 39%] Linking C shared library libxtrxll.so
[ 39%] Built target xtrxll
Scanning dependencies of target test_xtrxll
[ 40%] Building C object libxtrxll/tests/CMakeFiles/test_xtrxll.dir/test_xtrxll.c.o
[ 42%] Linking C executable test_xtrxll
[ 42%] Built target test_xtrxll
Scanning dependencies of target test_xtrxflash
[ 43%] Building C object libxtrxll/tests/CMakeFiles/test_xtrxflash.dir/test_xtrxflash.c.o
[ 45%] Linking C executable test_xtrxflash
[ 45%] Built target test_xtrxflash
Scanning dependencies of target xtrx_lms7002m
[ 46%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_time.c.o
[ 47%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_nco.c.o
[ 49%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_xbuf.c.o
[ 50%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_rbb.c.o
[ 52%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_rxtsp.c.o
[ 53%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_logger.c.o
[ 54%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_cgen.c.o
[ 56%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_filter_cal.c.o
[ 57%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_trf.c.o
[ 59%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_tbb.c.o
[ 60%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_afe.c.o
[ 61%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_txtsp.c.o
[ 63%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_tx_filter_cal.c.o
[ 64%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_vco.c.o
[ 66%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_gfir.c.o
[ 67%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_ldo.c.o
[ 69%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_lml.c.o
[ 70%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_impl.c.o
[ 71%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_sxx.c.o
[ 73%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_rfe.c.o
[ 74%] Building C object LMS7002M-driver/CMakeFiles/xtrx_lms7002m.dir/src/LMS7002M_rx_filter_cal.c.o
[ 76%] Linking C shared library libxtrx_lms7002m.so
[ 76%] Built target xtrx_lms7002m
[ 77%] Generating lms7002m_defs.h
Scanning dependencies of target lms7compact
[ 78%] Building C object liblms7002m/CMakeFiles/lms7compact.dir/liblms7002m.c.o
[ 80%] Linking C shared library liblms7compact.so
[ 80%] Built target lms7compact
Scanning dependencies of target xtrx
[ 81%] Building C object libxtrx/CMakeFiles/xtrx.dir/xtrx.c.o
[ 83%] Building C object libxtrx/CMakeFiles/xtrx.dir/xtrx_debug.c.o
[ 84%] Building C object libxtrx/CMakeFiles/xtrx.dir/xtrx_fe.c.o
[ 85%] Building C object libxtrx/CMakeFiles/xtrx.dir/xtrx_fe_nlms7.c.o
/home/hp/images/sources/libxtrx/xtrx_fe_nlms7.c:62:13: warning: ‘bparamu8_set_null’ defined but not used [-Wunused-function]
 static void bparamu8_set_null(xtrx_bparam_t* p)
             ^
/home/hp/images/sources/libxtrx/xtrx_fe_nlms7.c:67:13: warning: ‘bparamu8_set_val’ defined but not used [-Wunused-function]
 static void bparamu8_set_val(xtrx_bparam_t* p, unsigned val)
             ^
[ 87%] Linking C shared library libxtrx.so
[ 87%] Built target xtrx
Scanning dependencies of target test_xtrx
[ 88%] Building C object libxtrx/CMakeFiles/test_xtrx.dir/test_xtrx.c.o
[ 90%] Linking C executable test_xtrx
[ 90%] Built target test_xtrx
Scanning dependencies of target mainwindow_automoc
[ 91%] Automatic moc, uic and rcc for target mainwindow
Generating ui_mainwindow.h
Generating ui_mainwindow.h
Generating moc_mainwindow.cpp
Generating moc_rxthread.cpp
Generating moc_waterfall.cpp
[ 91%] Built target mainwindow_automoc
Scanning dependencies of target mainwindow
[ 92%] Building CXX object libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/mainwindow.cpp.o
In file included from /home/hp/images/sources/libxtrx/examples/xtrx_fft/mainwindow.cpp:20:0:
**/home/hp/images/sources/libxtrx/examples/xtrx_fft/mainwindow.h:25:22: fatal error: xtrx_api.h: No such file or directory**
compilation terminated.
libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/build.make:62: recipe for target 'libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/mainwindow.cpp.o' failed
make[2]: *** [libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/mainwindow.cpp.o] Error 1
CMakeFiles/Makefile2:830: recipe for target 'libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/all' failed
make[1]: *** [libxtrx/examples/xtrx_fft/CMakeFiles/mainwindow.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
hp@hp:~/images/sources/build$

**Comment by ducnguyenAstro** [comment]
Hi sergforce,

Come across the same problem. could you tell me how to apply the above patch?

Thanks

**Comment by ducnguyenAstro** [comment]
Just follow-up,

After changing CMakeLists.txt does not solve problem.
go to : /images/sources
manually  copy file: cp libxtrx/xtrx_api.h libxtrx/examples/xtrx_fft/
working properly.

Thanks,

**Comment by sergforce** [comment]
Thanks all!
There was one more miss, LIBXTRX_INCLUDE_DIRS wasn't set properly.

I committed and pushed already.
