### ISSUE TITLE
hi new compiler error

### ISSUE THREAD

**Issue by hmne** [xtrx-sdr/images#15]
> > [98%] Building C object libxtrx/CMakeFiles/test_xtrx.dir/test_xtrx.c.o
In file included from /root/images/sources/libxtrx/test_xtrx.c:37:
/root/images/sources/libxtrx/test_xtrx.c: In function ‘main’:
/root/images/sources/libxtrx/test_xtrx.c:632:10: error: ‘bprt’ undeclared (first use in this function); did you mean ‘bptr’?
   assert(bprt == out_buffs + rx_bufsize);
          ^~~~
/root/images/sources/libxtrx/test_xtrx.c:632:10: note: each undeclared identifier is reported only once for each function it appears in
At top level:
/root/images/sources/libxtrx/test_xtrx.c:56:22: warning: ‘testbuf’ defined but not used [-Wunused-const-variable=]
 static const int16_t testbuf[] =
                      ^~~~~~~
make[2]: *** [libxtrx/CMakeFiles/test_xtrx.dir/build.make:63: libxtrx/CMakeFiles/test_xtrx.dir/test_xtrx.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:729: libxtrx/CMakeFiles/test_xtrx.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by sergforce** [comment]
Thanks for the catch!

Updated
