### ISSUE TITLE
TX: high DC signal and transmitting in bursts

### ISSUE THREAD

**Issue by ducnguyenAstro** [xtrx-sdr/images#16]
Hi guys,

There are two things that i found when recently working with XTRX:
 -DC signal is always there (~ 12dbm) upon _powering XTRX up._(underlined nomore corrected)
--> **not always there but since after closing GRC, look like there is non-stopping running behind**.
- Transmitting signals always in bursts with error on terminal: 
"11:23:44.092663 ERROR:   xtrx_send_burst_sync[0]: TX DMA Current skip due to TO buffers: 2797, prev: 2796 TS:36667227 STPS:36675414"

Signals are all observed on Signal Analyzer.

Any comments or though are really appropriated to make this board more beautiful.
Cheers,

**Comment by sergforce** [comment]
I see you're using the old version. `test_xtrx` utility was updated, see the last comments about TO events here https://github.com/xtrx-sdr/images/issues/6

**Comment by ducnguyenAstro** [comment]
Thanks sergforce,

I will close this issue and move the conversation into the other. Sorry for not realizing they are both the same.
