### ISSUE TITLE
Rx tune fails "Unable to tune to VCO=1900000000"

### ISSUE THREAD

**Issue by takgr** [xtrx-sdr/images#23]
I don't know if this is the right place to open this issue, if not please let me know to move it.
Trying to tune XTRX to 950MHz, Rx tune fails and there is a core dump.
I use Soapy if that matters, and USB3 connection to XTRX

Debug log follows:

[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.12.0.0-0-unknown
15:28:37.574250 WARN:   xtrxllpciev0_discovery:238 [PCIE] XTRX PCIe driver isn't loaded
15:28:37.581611 DEBUG:  xtrxllusb3380v0_discovery:788 [USB3] usb3380: Found `usb3380://4/2/31` speed 5Gbit
15:28:37.582125 WARN:   xtrxllpciev0_discovery:238 [PCIE] XTRX PCIe driver isn't loaded
15:28:37.586811 DEBUG:  xtrxllusb3380v0_discovery:788 [USB3] usb3380: Found `usb3380://4/2/31` speed 5Gbit
[INFO] [UHDSoapyDevice] Make connection: 'usb3380://4/2/31'
15:28:37.737373 INFO:   [USB3] USB3380 dual fly GPEP RX mode is on, TX mode is on
15:28:37.737781 INFO:   [3380] USB338x Speed: 480 Mbps
15:28:37.747129 INFO:   [3380] Initialized PCIe dev 0100 [10ee:7012]
15:28:37.747425 WARN:   [3380] IO thread: Unable to set realtime priority: error 1
15:28:37.747484 INFO:   [3380] IO thread started
15:28:37.747658 INFO:   [CTRL] USB3_4/2/31: XTRX Rev4 (04000013)
15:28:37.747931 INFO:   [BPCI] USB3_4/2/31: RX DMA STOP MIMO (BLK:0 TS:0); TX DMA STOP MIMO
15:28:37.748176 INFO:   [USB3] USB3_4/2/31: Device `usb3380://4/2/31` was opened
CPU Features: SSE2+ SSE4.1+ AVX+ FMA-
15:28:37.959377 INFO:   [CTRL] USB3_4/2/31: LMS PMIC DCDC out set to V18=1880mV V33=3100mV V14=1480mV V12=1340mV
15:28:37.963628 INFO:   [CTRL] USB3_4/2/31: FPGA V_IO set to 1800mV
15:28:37.985819 INFO:   [LSM7] USB3_4/2/31: LMS VER:7 REV:1 MASK:1 (3841)
15:28:37.987142 INFO:   [DBGP] Starting XTRX debug thread
15:28:38.003919 INFO:   [XTRX] USB3_4/2/31: Set RefClk to 26000000 based on 25998830 measurement
15:28:38.003943 INFO:   [LMSF] USB3_4/2/31: Increase RXdiv= 4 TXdiv= 0 => CGEN 4.3 Mhz
15:28:38.003961 INFO:   [LMSF] USB3_4/2/31: Increase RXdiv= 8 TXdiv= 0 => CGEN 8.7 Mhz
15:28:38.003970 INFO:   [LMSF] USB3_4/2/31: Increase RXdiv=16 TXdiv= 0 => CGEN 17.3 Mhz
15:28:38.003980 INFO:   [LMSF] USB3_4/2/31: Increase RXdiv=32 TXdiv= 0 => CGEN 34.7 Mhz
15:28:38.004002 INFO:   [LSM7] USB3_4/2/31: CGEN: VCO/2=1178666644 k/2=34 int=90 frac=699048
15:28:38.006879 INFO:   [LSM7] USB3_4/2/31: CGEN: binary result: 159
15:28:38.009253 INFO:   [LSM7] USB3_4/2/31: CGEN: Retuned [160:166] -> 163
15:28:38.010962 INFO:   [CTRL] USB3_4/2/31: FPGA V_IO set to 1800mV
15:28:38.010969 INFO:   [LMSF] USB3_4/2/31: rxrate=0.271MHz txrate=0.000MHz actual_master=34.667MHz rxdecim=32(h_1) txinterp=1(h_1) RX_ADC=8.667MHz TX_DAC=4.333MHz hintr=0 hdecim=0 delay=0 NRXFWD=0 LML1HID=3 LML2HID=1 RX_div=0 TX_div=0 RX_TSP_div=16 TX_TSP_div=1 FclkRX=0.000 (PHS=0) RXx2=0
15:28:38.011316 INFO:   [LMSF] USB3_4/2/31: Set gain 20.8 to 0 on 1 channel
15:28:38.011423 INFO:   [LSM7] USB3_4/2/31: RFE: set_lna(9 -> 9) => 8
15:28:38.011559 INFO:   [LMSF] USB3_4/2/31: Set gain 0.0 to 1 on 1 channel
15:28:38.011579 INFO:   [LMSF] USB3_4/2/31: Set gain 0.0 to 2 on 1 channel
15:28:38.011590 INFO:   [LSM7] USB3_4/2/31: RBB: set_pga(12) rcc_ctl -> 23, c_ctl -> 2
15:28:38.011828 INFO:   [LMSF] USB3_4/2/31: Set RX band to 2 (L)
15:28:38.012336 INFO:   [CTRL] USB3_4/2/31: RX_ANT: 1 TX_ANT: 0
15:28:38.012400 INFO:   [BPCI] USB3_4/2/31: RX DMA STOP MIMO (BLK:0 TS:0); TX DMA SKIP MIMO
15:28:38.012568 INFO:   [LSM7] USB3_4/2/31: 0x0124[00, 00]
15:28:38.013339 INFO:   [BPCI] USB3_4/2/31: RX DMA STOP MIMO (BLK:0 TS:0); TX DMA SKIP MIMO
15:28:38.013454 INFO:   [LMSF] USB3_4/2/31: Set RX band to 2 (L)
15:28:38.013964 INFO:   [CTRL] USB3_4/2/31: RX_ANT: 1 TX_ANT: 0
15:28:38.014164 INFO:   [LMSF] USB3_4/2/31: Set gain 20.8 to 0 on 1 channel
15:28:38.014172 INFO:   [LSM7] USB3_4/2/31: RFE: set_lna(9 -> 9) => 8
15:28:38.014350 INFO:   [LMSF] USB3_4/2/31: Set gain 0.0 to 1 on 1 channel
15:28:38.014381 INFO:   [LMSF] USB3_4/2/31: Set gain 0.0 to 2 on 1 channel
15:28:38.014391 INFO:   [LSM7] USB3_4/2/31: RBB: set_pga(12) rcc_ctl -> 23, c_ctl -> 2
15:28:38.014743 INFO:   [LMSF] USB3_4/2/31: FE_FREQ rx=1 type=0 freq=950000000.000000 ch=3
15:28:38.015299 INFO:   [LSM7] USB3_4/2/31: SXR: initial VCO=1900000000 DIVH=1 VCOs:0001
15:28:38.015307 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.017501 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 129
15:28:38.018809 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.021001 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.022308 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.024881 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.026366 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.028629 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.030101 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.032404 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.033814 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.036003 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.037438 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.039628 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.040935 INFO:   [LSM7] USB3_4/2/31: SXX: VCO3 N=36 frac=564617
15:28:38.043129 INFO:   [LSM7] USB3_4/2/31: SXX: binary result: 1
15:28:38.044431 INFO:   [LSM7] USB3_4/2/31: SXR: Unable to tune to VCO=1900000000
terminate called after throwing an instance of 'std::runtime_error'
  what():  SoapyXTRX::setFrequency(RF) unable to tune!
Aborted (core dumped)

**Comment by sergforce** [comment]
This was just a software bug. Update all libs to the latest revision.
