### ISSUE TITLE
OpenBTS and OpenLTE

### ISSUE THREAD

**Issue by Peterthegreat** [xtrx-sdr/images#38]
Hello

Is there any support for OpenBTS or OpenLTE for XTRX? maybe using the USB3 adapter?

> **LTE Cellular**
> The combination of XTRX’s accurate, stable clock, on-board GPSDO, and low-latency PCIe bus makes LTE possible out of the box.

**Comment by sergforce** [comment]
We haven't tested OpenBTS & OpenLTE.

Right now Amarisfot LTE works best. We're working to get srsLTE & OAI support as well

**Comment by Peterthegreat** [comment]
Thanks!
Any software is fine. Glad to hear that it's a work in progress

**Comment by joeldelosangeles** [comment]
Hi Sergeforce, 

We use UMTrx for our GSM base stations (we just ordered 40 units recently).

Any update on development in using xtrx for srsLTE or OAI?  We have 2 units of XTRX CS.  We won't mind working with XTRX Pro if needed as long as srsLTE or OAI is used.

Thanks,
Joel Delos Angeles

**Comment by Dastgsm** [comment]
How about OAI and OAI5G-NR support over xtrx?
