### ISSUE TITLE
XTRX missing from Gnuradio

### ISSUE THREAD

**Issue by BartE186** [xtrx-sdr/images#47]
Hi,

I'm having issues compiling the Gr-OsmoSDR from git.
When trying to follow the instructions to the letter:
git clone git://git.osmocom.org/gr-osmosdr
cd gr-osmosdr/
mkdir build
cd build/
cmake ../

I get this error:
"
CMake Error at CMakeLists.txt:156 (MESSAGE):
  GnuRadio version required: >="3.7.10" found: "3.7.9.1"
"

I've also tried the libxtrx and master branches.

This is the output for both:
"
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Configuring Boost C++ Libraries...
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
-- Checking for module 'gnuradio-blocks'
--   Found gnuradio-blocks, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-blocks.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_BLOCKS: /usr/lib/x86_64-linux-gnu/libgnuradio-blocks.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: PMT
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_PMT: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_PMT_FOUND = TRUE
-- Checking for module 'gnuradio-iqbalance'
--   Found gnuradio-iqbalance, version 0
-- Found GNURADIO_IQBALANCE: /usr/lib/x86_64-linux-gnu/libgnuradio-iqbalance.so  
-- Checking for module 'uhd'
--   No package 'uhd' found
-- Checking for module 'gnuradio-uhd'
--   Found gnuradio-uhd, version 3.7.9
-- Found gnuradio-uhd: /usr/include, /usr/lib/x86_64-linux-gnu/libgnuradio-uhd.so
-- Found GNURADIO_UHD: /usr/lib/x86_64-linux-gnu/libgnuradio-uhd.so  
-- Checking for module 'gnuradio-fcd'
--   Found gnuradio-fcd, version 3.7.9
-- Found gnuradio-fcd: /usr/include, /usr/lib/x86_64-linux-gnu/libgnuradio-fcd.so
-- Found GNURADIO_FCD: /usr/lib/x86_64-linux-gnu/libgnuradio-fcd.so  
-- Checking for module 'gnuradio-fcdproplus'
--   Found gnuradio-fcdproplus, version 0.0.1
-- Found gnuradio-fcdproplus: /usr/include, /usr/lib/x86_64-linux-gnu/libgnuradio-fcdproplus.so
-- Found GNURADIO_FCDPP: /usr/lib/x86_64-linux-gnu/libgnuradio-fcdproplus.so  
-- Checking for module 'libosmosdr'
--   No package 'libosmosdr' found
-- libosmosdr not found.
-- Checking for module 'librtlsdr'
--   Found librtlsdr, version 0.5.3
-- Found librtlsdr: /usr/include, /usr/lib/x86_64-linux-gnu/librtlsdr.so
-- Checking for module 'libmirisdr'
--   No package 'libmirisdr' found
-- libmirisdr not found.
-- Checking for module 'libhackrf'
--   No package 'libhackrf' found
-- Could NOT find LIBHACKRF (missing:  LIBHACKRF_LIBRARIES LIBHACKRF_INCLUDE_DIRS) 
-- Checking for module 'libairspy'
--   No package 'libairspy' found
-- Could NOT find LIBAIRSPY (missing:  LIBAIRSPY_LIBRARIES LIBAIRSPY_INCLUDE_DIRS) 
-- Checking for module 'volk'
--   Found volk, version 1.1
-- Found VOLK: /usr/lib/x86_64-linux-gnu/libvolk.so  
-- Checking for module 'libbladeRF'
--   No package 'libbladeRF' found
-- libbladeRF not found.
CMake Warning at CMakeLists.txt:174 (find_package):
  Could not find a package configuration file provided by "SoapySDR" with any
  of the following names:

    SoapySDRConfig.cmake
    soapysdr-config.cmake

  Add the installation prefix of "SoapySDR" to CMAKE_PREFIX_PATH or set
  "SoapySDR_DIR" to a directory containing one of the above files.  If
  "SoapySDR" provides a separate development package or SDK, be sure it has
  been installed.

-- Checking for module 'libfreesrp'
--   No package 'libfreesrp' found
-- libfreesrp not found.
-- Checking for module 'libxtrx'
--   Found libxtrx, version 
-- Found libxtrx: /usr/local/include, /usr/local/lib/libxtrx.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- 
-- Checking for module SWIG
-- Disabling SWIG because version check failed.
-- 
-- The build system will automatically enable all components.
-- Use -DENABLE_DEFAULT=OFF to disable components by default.
-- 
-- Configuring Python support support...
--   Dependency PYTHONLIBS_FOUND = TRUE
--   Dependency SWIG_FOUND = FALSE
--   Dependency SWIG_VERSION_CHECK = FALSE
--   Disabling Python support support.
--   Override with -DENABLE_PYTHON=ON/OFF
-- 
-- Configuring high resolution timing...
-- Performing Test HAVE_CLOCK_GETTIME
-- Performing Test HAVE_CLOCK_GETTIME - Success
-- Performing Test HAVE_MACH_ABSOLUTE_TIME
-- Performing Test HAVE_MACH_ABSOLUTE_TIME - Failed
-- Performing Test HAVE_QUERY_PERFORMANCE_COUNTER
-- Performing Test HAVE_QUERY_PERFORMANCE_COUNTER - Failed
--   High resolution timing supported through clock_gettime.
-- 
-- Configuring Osmocom IQ Imbalance Correction support...
--   Dependency GNURADIO_IQBALANCE_FOUND = TRUE
--   Enabling Osmocom IQ Imbalance Correction support.
--   Override with -DENABLE_IQBALANCE=ON/OFF
-- 
-- Configuring sysmocom OsmoSDR support...
--   Dependency LIBOSMOSDR_FOUND = FALSE
--   Disabling sysmocom OsmoSDR support.
--   Override with -DENABLE_OSMOSDR=ON/OFF
-- 
-- Configuring FUNcube Dongle support...
--   Dependency GNURADIO_FCD_FOUND = TRUE
--   Enabling FUNcube Dongle support.
--   Override with -DENABLE_FCD=ON/OFF
-- 
-- Configuring FUNcube Dongle Pro+ support...
--   Dependency GNURADIO_FCDPP_FOUND = TRUE
--   Enabling FUNcube Dongle Pro+ support.
--   Override with -DENABLE_FCDPP=ON/OFF
-- 
-- Configuring IQ File Source & Sink support...
--   Dependency GNURADIO_BLOCKS_FOUND = TRUE
--   Enabling IQ File Source & Sink support.
--   Override with -DENABLE_FILE=ON/OFF
-- 
-- Configuring Osmocom RTLSDR support...
--   Dependency LIBRTLSDR_FOUND = TRUE
--   Enabling Osmocom RTLSDR support.
--   Override with -DENABLE_RTL=ON/OFF
-- 
-- Configuring RTLSDR TCP Client support...
--   Dependency GNURADIO_BLOCKS_FOUND = TRUE
--   Enabling RTLSDR TCP Client support.
--   Override with -DENABLE_RTL_TCP=ON/OFF
-- 
-- Configuring Ettus USRP Devices support...
--   Dependency UHD_FOUND = 0
--   Dependency GNURADIO_UHD_FOUND = TRUE
--   Disabling Ettus USRP Devices support.
--   Override with -DENABLE_UHD=ON/OFF
-- 
-- Configuring Osmocom MiriSDR support...
--   Dependency LIBMIRISDR_FOUND = FALSE
--   Disabling Osmocom MiriSDR support.
--   Override with -DENABLE_MIRI=ON/OFF
-- 
-- Configuring HackRF & rad1o Badge support...
--   Dependency LIBHACKRF_FOUND = FALSE
--   Disabling HackRF & rad1o Badge support.
--   Override with -DENABLE_HACKRF=ON/OFF
-- 
-- Configuring nuand bladeRF support...
--   Dependency LIBBLADERF_FOUND = FALSE
--   Disabling nuand bladeRF support.
--   Override with -DENABLE_BLADERF=ON/OFF
-- 
-- Configuring RFSPACE Receivers support...
--   Enabling RFSPACE Receivers support.
--   Override with -DENABLE_RFSPACE=ON/OFF
-- 
-- Configuring AIRSPY Receiver support...
--   Dependency LIBAIRSPY_FOUND = FALSE
--   Disabling AIRSPY Receiver support.
--   Override with -DENABLE_AIRSPY=ON/OFF
-- 
-- Configuring SoapySDR support support...
--   Dependency SoapySDR_FOUND = 0
--   Disabling SoapySDR support support.
--   Override with -DENABLE_SOAPY=ON/OFF
-- 
-- Configuring Red Pitaya SDR support...
--   Enabling Red Pitaya SDR support.
--   Override with -DENABLE_REDPITAYA=ON/OFF
-- 
-- Configuring FreeSRP support support...
--   Dependency LIBFREESRP_FOUND = FALSE
--   Disabling FreeSRP support support.
--   Override with -DENABLE_FREESRP=ON/OFF
-- 
-- Configuring XTRX SDR support...
--   Dependency LIBXTRX_FOUND = TRUE
--   Enabling XTRX SDR support.
--   Override with -DENABLE_XTRX=ON/OFF
-- 
-- ######################################################
-- # Gnuradio enabled components                         
-- ######################################################
--   * Osmocom IQ Imbalance Correction
--   * FUNcube Dongle
--   * FUNcube Dongle Pro+
--   * IQ File Source & Sink
--   * Osmocom RTLSDR
--   * RTLSDR TCP Client
--   * RFSPACE Receivers
--   * Red Pitaya SDR
--   * XTRX SDR
-- 
-- ######################################################
-- # Gnuradio disabled components                        
-- ######################################################
--   * Python support
--   * sysmocom OsmoSDR
--   * Ettus USRP Devices
--   * Osmocom MiriSDR
--   * HackRF & rad1o Badge
--   * nuand bladeRF
--   * AIRSPY Receiver
--   * SoapySDR support
--   * FreeSRP support
-- 
-- Building for version: v0.1.x-xxx-xunknown / 0.1.5git
-- Using install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sintela/gr-osmosdr-libxtrx/build
sintela@sintela-System-Product-Name:~/gr-osmosdr-libxtrx/build$ make
Scanning dependencies of target gnuradio-osmosdr
[  5%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/source_impl.cc.o
[ 11%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/sink_impl.cc.o
[ 16%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/ranges.cc.o
[ 22%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/device.cc.o
[ 27%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/time_spec.cc.o
[ 33%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/fcd/fcd_source_c.cc.o
[ 38%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/file/file_source_c.cc.o
[ 44%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/file/file_sink_c.cc.o
[ 50%] Building CXX object lib/CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o
/home/sintela/gr-osmosdr-libxtrx/lib/rtl/rtl_source_c.cc: In constructor ‘rtl_source_c::rtl_source_c(const string&)’:
/home/sintela/gr-osmosdr-libxtrx/lib/rtl/rtl_source_c.cc:224:43: error: ‘rtlsdr_set_bias_tee’ was not declared in this scope
   ret = rtlsdr_set_bias_tee(_dev, bias_tee);
                                           ^
lib/CMakeFiles/gnuradio-osmosdr.dir/build.make:254: recipe for target 'lib/CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/rtl/rtl_source_c.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-osmosdr.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-osmosdr.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
"

I've tried excluding the RTL_Source from the process but this resulted in Gnuradio giving me this error :
"
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy redpitaya 
FATAL: No supported devices found to pick from. 
"

Eearlier durig the install process I've come across couple of small issues
Running: 
test_xtrx -t -l2
gave me this error 
test_xtrx: command not found
Is this an issue? Should there be a link to it?

cd '/usr/local/lib/xtrx'
./test_xtrx -t -l2
#15:10:24.324309 ERROR:  [PCIE] Can't open device `/dev/xtrx0`: Permission denied
#Failed xtrx_open: -19

sudo ./test_xtrx -t -l2
#CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
#Master: 32.000 MHz; RX rate: 4.000 MHz; TX rate: 0.000 MHz
#RX tunned: 900000000.000000
#RX bandwidth: 2000000.000000
#RX LNA gain: 15.000000
#RX PGA gain: 0.000000
#RX TIA gain: 9.000000
#RX CYCLES=1 SAMPLES=16384 SLICE=16384 (PARTS=1)
#PROCESSED RX SLICE 0 /0: res 0 TS:    8192       4229 us DELTA      3 us LATE   2185 us 16384 #samples
#RX STAT Overruns:0
#Success!
#Processed 1 devs, each: RX 2 x 1.933 = 3.865 MSPS (WIRE: 15.461600)    TX 2 x 0.000 = 0.000 MSPS ##(WIRE: 0.000000 MB/s) 

Has anyone come across these issues ?
Any help will be much appreciated.

Operating System: Ubuntu 16.04.6 LTS
Kernel: Linux 4.15.0-47-generic
Architecture: x86-64
cmake version 3.5.1
Gcc 4:5.3.1-1ubuntu1
Gnuradio 3.7.9-2ubuntu1

**Comment by o8ko8k** [comment]
cmake .. | grep FALSE  should yield 

 Dependency SWIG_FOUND = FALSE
-- Dependency SWIG_VERSION_CHECK = FALSE
 Dependency LIBOSMOSDR_FOUND = FALSE

among other things (airspy and such which i expect they should be).  I would conclude you go install SWIG and libosmosdr   

if your using ubuntu or its variants consider installing synaptic and managing your dependencies with that tool.  i found it helpful.  i believe you will need the -dev variant of SWIG and libosmosdr in order to get those items to clear.

I presume you either figured this out already or gave up. but someone may find this post helpful.

**Comment by chemeris** [comment]
@o8ko8k Thanks a lot for helping answer this!
I'm closing this issue so far.
