### ISSUE TITLE
GPS testing

### ISSUE THREAD

**Issue by yahoo2016** [xtrx-sdr/images#53]
There is a "GPS" input connector on XTRX, how can I test GPS functions (1PPS, NMEA) after I connect an GPS antenna to "GPS" input?

**Comment by satunnainen** [comment]
1. Install XTRX driver and libraries (use [pre-built packages](https://github.com/xtrx-sdr/images/blob/master/README.md#pre-built-packages) or build them from sources).
2. Install `gpsd` and `gpsd-clients` (for example, with `apt`).
3. Run `gpsd` with `/dev/ttyXTRX0` specified as the device (in Debian-based distros you can specify device in `/etc/default/gpsd` file and restart `gpsd` service).
4. Connect your antenna.
5. Run `cgps` and wait.

**Comment by yahoo2016** [comment]
It worked. Thanks!
