### ISSUE TITLE
gr-osmosdr xtrx branch build instructions 

### ISSUE THREAD

**Issue by o8ko8k** [xtrx-sdr/images#67]
**The build instructions from gr-osmosdr README file were copied directly over from the original gr-osmosdr branch (see below snipit).  please add a xtrx branch specific README as an alternative to prevent people from building off the original branch.  (I did this, and it took me a few days to figure out what happened)  This may be related to other posts as well.**

Building with cmake:

git clone git://git.osmocom.org/gr-osmosdr                #  <---- remove this line
**git clone https://github.com/xtrx-sdr/gr-osmosdr       #  <----  Replace with this line**
cd gr-osmosdr/
mkdir build
cd build/
cmake ../
make
sudo make install
sudo ldconfig

NOTE: The osmocom blocks will appear under 'Sources' and 'Sinks' categories
in GRC menu._

**Comment by chemeris** [comment]
Thanks a lot! Fixed
