### ISSUE TITLE
ERROR:   xtrx_debug: Unable to create FIFO, error -2

### ISSUE THREAD

**Issue by gustad** [xtrx-sdr/images#7]
When I run test_xtrx -t -l2 I get:

```
22:14:21.554913 ERROR:   USB3380: Unable to open USB3380!
22:14:21.555003 ERROR:   Unable to allocate USB3380 context: error: -6
CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
22:14:21.557911 WARNING: NLMS7 PCI_3: LMS VER:7 REV:1 MASK:1 (13841)
22:14:21.557932 ERROR:   xtrx_debug: Unable to create FIFO, error -2
22:14:21.557935 ERROR:   Failed to initialize debug service: err=-2
Failed xtrx_open: -2
```
Are there any forums available for XTRX users? The above might as well be a user error as I don't even know if the FPGA is pre-loaded or if it has to be loaded with a specific image version.

**Comment by sergforce** [comment]
We're working on getting a forum

The test file was attempting to create a pipe debug interface and failed. Make it optional.

feel free to reopen if any problem is discovered
