### ISSUE TITLE
Problem with xtrx/Amarisoft ABI version

### ISSUE THREAD

**Issue by globaltel** [xtrx-sdr/images#77]
Hello,

I am trying to test the xtrx with Amarisoft stack and i got an error messageabout ABI version.

here are the logs of Amarisoft Enb:

./lteenb config/enb.cfg
LTE Base Station version 2019-09-30, Copyright (C) 2012-2019 Amarisoft
log file.rotate=50M,file.path=/var/log/lte/
t
This software is licensed to XXXXXX.
Support and software update available until 2020-02-08.
CPU Features: SSE2+ SSE4.1+ AVX+ FMA+
Using avx for xtrxdsp_iq16_sc32
Using avx for xtrxdsp_iq8_ic16
Using avx for xtrxdsp_iq16_ic16i
Using avx for xtrxdsp_iq8_ic8i
Using avx for xtrxdsp_sc32i_iq16
Using avx for xtrxdsp_iq8_sc32
Using avx for xtrxdsp_iq8_sc32i
Using avx for xtrxdsp_iq16_sc32i
Using avx for xtrxdsp_sc32_iq16
Using avx for xtrxdsp_ic16i_iq16
FAIRWAVES XTRX EXPERIMENTAL DRIVER!
ABI compatibility mismatch between LTEENB and TRX XTRX driver (LTEENB ABI version=15, TRX XTRX driver ABI version=13)
Could not initialize RF driver

**Comment by chemeris** [comment]
Please try with the latest commit and re-open the issue if it doesn't work.
